build:
    nodes:
        tests-coverage:
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --testsuite unit --coverage-clover=clover.xml'
                        coverage:
                            file: 'clover.xml'
                            format: 'clover'

        tests-integration:
            environment:
                mysql: 5.7
                redis: true
            dependencies:
                before:
                    - mysql -e "CREATE DATABASE bernard_scheduler_test;"
                    - pecl install redis
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit --testsuite integration'

        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }